### ISSUE TITLE
Notificação enviada quando é feito login como admin

### ISSUE THREAD

**Issue by cenourinha** [whmcsred/login_avisa#1]
Quando um administrador efectua autenticação na conta utilizando "Login as a client", a notification é igualmente enviada para o cliente. Será ideal implementar uma excepção para este caso.

**Comment by whmcsred** [comment]
Iremos verificar e ajeitar de acordo com a sua sugestão.

**Comment by whmcsred** [comment]
Olá cenourinha, informamos que a atualização corrente já existe a função em funcionamento, no caso um administrador esteja logado e deseja logar na conta do cliente, o cliente não sera informado nesse caso.
